# Generated by Django 5.0 on 2025-12-14 22:12

import django.db.models.deletion
import painel.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria vinda do ERP', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Família de Produto',
                'verbose_name_plural': 'Famílias de Produtos',
            },
        ),
        migrations.CreateModel(
            name='VideoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Oferta Fundo Vermelho', max_length=100)),
                ('arquivo_video', models.FileField(help_text='Vídeo de fundo (MP4 leve)', upload_to='templates_video/')),
                ('titulo_top', models.IntegerField(default=10, help_text='% do topo para o Título', validators=[painel.models.validar_porcentagem])),
                ('titulo_left', models.IntegerField(default=50, help_text='% da esquerda para o Título', validators=[painel.models.validar_porcentagem])),
                ('titulo_cor', models.CharField(default='#FFFFFF', help_text='Cor Hexadecimal (Ex: #FFFFFF)', max_length=7)),
                ('titulo_tamanho', models.CharField(default='5vw', help_text='Tamanho da fonte (ex: 5vw, 40px)', max_length=10)),
                ('preco_top', models.IntegerField(default=50, help_text='% do topo para o Preço', validators=[painel.models.validar_porcentagem])),
                ('preco_left', models.IntegerField(default=50, help_text='% da esquerda para o Preço', validators=[painel.models.validar_porcentagem])),
                ('preco_cor', models.CharField(default='#FFD700', help_text='Cor Hexadecimal (Ex: #FFD700)', max_length=7)),
                ('preco_tamanho', models.CharField(default='8vw', help_text='Tamanho da fonte (ex: 8vw)', max_length=10)),
                ('img_top', models.IntegerField(default=30, help_text='% do topo para a Imagem', validators=[painel.models.validar_porcentagem])),
                ('img_left', models.IntegerField(default=10, help_text='% da esquerda para a Imagem', validators=[painel.models.validar_porcentagem])),
                ('img_width', models.IntegerField(default=20, help_text='Largura da imagem em % da tela', validators=[painel.models.validar_porcentagem])),
            ],
            options={
                'verbose_name': 'Template de Vídeo',
                'verbose_name_plural': 'Templates de Vídeo',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: TV do Açougue', max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modo_exibicao', models.CharField(choices=[('TABELA', 'Apenas Tabela de Preços'), ('VIDEO', 'Apenas Vídeos de Oferta'), ('MISTO', 'Tabela + Vídeos Intercalados')], default='TABELA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exibir_apenas_familias', models.ManyToManyField(blank=True, help_text='Se vazio, mostra tudo. Se selecionado, filtra apenas essas categorias.', to='painel.familiaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('em_oferta', models.BooleanField(default=False)),
                ('exibir_no_painel', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='painel.familiaproduto')),
                ('template_video', models.ForeignKey(blank=True, help_text='Selecione um template para exibir este produto como oferta em vídeo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='painel.videotemplate')),
            ],
            options={
                'ordering': ['descricao'],
            },
        ),
    ]
