# Generated by Django 5.0 on 2026-02-20 00:40

import django.db.models.deletion
import painel.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da empresa ou cliente', max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='FamiliaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria vinda do ERP', max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='painel.empresa')),
            ],
            options={
                'verbose_name': 'Família de Produto',
                'verbose_name_plural': 'Famílias de Produtos',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: TV do Açougue', max_length=100)),
                ('titulo_exibicao', models.CharField(blank=True, help_text='Título exibido no topo da TV. Se vazio, usa o Nome.', max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_acesso', models.CharField(default=painel.models.gerar_codigo_curto, editable=False, max_length=6, unique=True)),
                ('playlist', models.JSONField(blank=True, default=list, help_text='Lista ordenada de itens (Mídias e Tabelas) para reprodução.')),
                ('orientacao', models.CharField(choices=[('HORIZONTAL', 'Horizontal (Padrão 16:9)'), ('VERTICAL_DIR', 'Vertical 9:16 (Giro 90° Direita)'), ('VERTICAL_ESQ', 'Vertical 9:16 (Giro 90° Esquerda)')], default='HORIZONTAL', max_length=20)),
                ('modo_exibicao', models.CharField(choices=[('TABELA', 'Apenas Tabela de Preços'), ('VIDEO', 'Apenas Mídia'), ('MISTO', 'Híbrido (Legado)'), ('PLAYLIST', 'Playlist Personalizada')], default='PLAYLIST', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='painel.empresa')),
                ('exibir_apenas_familias', models.ManyToManyField(blank=True, to='painel.familiaproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Identificação interna para organização', max_length=100)),
                ('arquivo', models.FileField(upload_to='midias/')),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('IMAGEM', 'Imagem')], editable=False, max_length=10)),
                ('duracao', models.IntegerField(default=15, help_text='Duração padrão em segundos para exibição')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='painel.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='painel.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição na TV (Menor número aparece primeiro)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('em_oferta', models.BooleanField(default=False)),
                ('exibir_no_painel', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='painel.empresa')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='painel.familiaproduto')),
            ],
            options={
                'ordering': ['descricao'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
