# Generated by Django 5.0 on 2025-12-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotemplate',
            options={},
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='rotacao_tela',
            field=models.CharField(choices=[('0', '0º - Paisagem (Padrão)'), ('90', '90º - Retrato (Vertical Direita)'), ('180', '180º - Paisagem Invertida'), ('270', '270º - Retrato (Vertical Esquerda)')], default='0', help_text='Ajuste conforme a instalação física da TV', max_length=10),
        ),
        migrations.AddField(
            model_name='videotemplate',
            name='estilo_texto',
            field=models.CharField(choices=[('NORMAL', 'Normal (Apenas Sombra)'), ('OUTLINE', 'Contorno Preto (Outline)'), ('BOX', 'Fundo Retangular (Box)'), ('GLOW', 'Brilho Neon')], default='NORMAL', help_text='Estilo visual para garantir leitura sobre o vídeo', max_length=20),
        ),
        migrations.AddField(
            model_name='videotemplate',
            name='img_height',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='videotemplate',
            name='titulo_width',
            field=models.FloatField(default=80, help_text='Largura da área de texto (%)'),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='arquivo_video',
            field=models.FileField(upload_to='templates_video/'),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_left',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_top',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_width',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_cor',
            field=models.CharField(default='#FFD700', max_length=7),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_left',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_tamanho',
            field=models.CharField(default='8vw', max_length=10),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_top',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_cor',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_left',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_tamanho',
            field=models.CharField(default='5vw', max_length=10),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_top',
            field=models.FloatField(default=10),
        ),
    ]
