# Generated by Django 5.0 on 2026-03-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Usuário master/dono da conta'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado')], default='PENDENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nome',
            field=models.CharField(help_text='Identificação do local físico do dispositivo.', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='playlist',
            field=models.JSONField(blank=True, default=list, help_text='Estrutura de dados serializada contendo a fila de mídias e tabelas.'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='titulo_exibicao',
            field=models.CharField(blank=True, help_text="Header de exibição na UI. Faz fallback para o campo 'nome' se nulo.", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(help_text='Razão social ou nome fantasia da empresa.', max_length=150),
        ),
        migrations.AlterField(
            model_name='familiaproduto',
            name='nome',
            field=models.CharField(help_text='Nomenclatura da categoria/família originada do ERP.', max_length=100),
        ),
        migrations.AlterField(
            model_name='midia',
            name='duracao',
            field=models.IntegerField(default=15, help_text='Tempo de exibição (TTL) em segundos no client.'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='nome',
            field=models.CharField(help_text='Identificador interno do asset.', max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Peso de ordenação na renderização UI (Crescente).'),
        ),
    ]
