# Generated by Django 5.0 on 2025-12-17 02:08

import painel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_alter_videotemplate_options_dispositivo_rotacao_tela_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotemplate',
            options={'verbose_name': 'Template de Vídeo', 'verbose_name_plural': 'Templates de Vídeo'},
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='rotacao_tela',
        ),
        migrations.RemoveField(
            model_name='videotemplate',
            name='estilo_texto',
        ),
        migrations.RemoveField(
            model_name='videotemplate',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='videotemplate',
            name='titulo_width',
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='arquivo_video',
            field=models.FileField(help_text='Vídeo de fundo (MP4 leve)', upload_to='templates_video/'),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_left',
            field=models.IntegerField(default=10, help_text='% da esquerda para a Imagem', validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_top',
            field=models.IntegerField(default=30, help_text='% do topo para a Imagem', validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_width',
            field=models.IntegerField(default=20, help_text='Largura da imagem em % da tela', validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='nome',
            field=models.CharField(help_text='Ex: Oferta Fundo Vermelho', max_length=100),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_cor',
            field=models.CharField(default='#FFD700', help_text='Cor Hexadecimal (Ex: #FFD700)', max_length=7),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_left',
            field=models.IntegerField(default=50, help_text='% da esquerda para o Preço', validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_tamanho',
            field=models.CharField(default='8vw', help_text='Tamanho da fonte (ex: 8vw)', max_length=10),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_top',
            field=models.IntegerField(default=50, help_text='% do topo para o Preço', validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_cor',
            field=models.CharField(default='#FFFFFF', help_text='Cor Hexadecimal (Ex: #FFFFFF)', max_length=7),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_left',
            field=models.IntegerField(default=50, help_text='% da esquerda para o Título', validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_tamanho',
            field=models.CharField(default='5vw', help_text='Tamanho da fonte (ex: 5vw, 40px)', max_length=10),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_top',
            field=models.IntegerField(default=10, help_text='% do topo para o Título', validators=[painel.models.validar_porcentagem]),
        ),
    ]
