# Generated by Django 5.0 on 2026-06-09 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_convite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Título customizado que aparecerá no cabeçalho da TV.', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_personalizadas', to='painel.empresa')),
            ],
            options={
                'verbose_name': 'Lista Personalizada',
                'verbose_name_plural': 'Listas Personalizadas',
            },
        ),
        migrations.CreateModel(
            name='ListaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0, help_text='Posição do produto dentro da lista')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='painel.listapersonalizada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.produto')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('lista', 'produto')},
            },
        ),
    ]
