# Generated by Django 5.0 on 2025-12-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_alter_videotemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='orientacao',
            field=models.CharField(choices=[('HORIZONTAL', 'Horizontal (Padrão 16:9)'), ('VERTICAL_DIR', 'Vertical 9:16 (Giro 90° Direita)'), ('VERTICAL_ESQ', 'Vertical 9:16 (Giro 90° Esquerda)')], default='HORIZONTAL', help_text='Escolha conforme a instalação física da TV', max_length=20),
        ),
    ]
