# Generated by Django 5.0 on 2025-12-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_dispositivo_orientacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotemplate',
            name='layout_data',
            field=models.JSONField(blank=True, default=dict, help_text='Configuração gerada pelo Editor Visual'),
        ),
    ]
