# Generated by Django 5.0 on 2025-12-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_videotemplate_layout_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotemplate',
            name='layout_data',
        ),
    ]
