# Generated by Django 5.0 on 2026-06-10 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_add_token_verificacao_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='omie_app_key',
            field=models.CharField(blank=True, help_text='App Key gerada no painel do Omie', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='omie_app_secret',
            field=models.CharField(blank=True, help_text='App Secret gerado no painel do Omie', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SincronizacaoOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('CONCLUIDA', 'Concluída'), ('ERRO', 'Erro na Sincronização')], default='PENDENTE', max_length=20)),
                ('dados', models.JSONField(default=dict, help_text='Payload JSON processado contendo os novos produtos, alterações de preço, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sincronizacoes_omie', to='painel.empresa')),
            ],
            options={
                'verbose_name': 'Sincronização Omie',
                'verbose_name_plural': 'Sincronizações Omie',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoIgnoradoOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código do produto no ERP', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_ignorados_omie', to='painel.empresa')),
            ],
            options={
                'verbose_name': 'Produto Ignorado Omie',
                'verbose_name_plural': 'Produtos Ignorados Omie',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
