# Generated by Django 5.0 on 2026-06-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_omie_integration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoignoradoomie',
            name='descricao',
            field=models.CharField(blank=True, help_text='Nome do produto no momento em que foi ignorado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produtoignoradoomie',
            name='familia',
            field=models.CharField(blank=True, help_text='Família do produto no momento em que foi ignorado', max_length=150, null=True),
        ),
    ]
