# Generated by Django 5.0 on 2025-12-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_remove_videotemplate_layout_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotemplate',
            name='elementos_extras',
            field=models.JSONField(blank=True, default=list, help_text='Elementos extras adicionados no editor visual'),
        ),
        migrations.AddField(
            model_name='videotemplate',
            name='estilos_css',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações avançadas de estilo (JSON)'),
        ),
    ]
