# Generated by Django 6.0.6 on 2026-08-01 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_add_denylist_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamiliaIgnoradaOmie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, help_text='Nome exato da família no Omie', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias_ignoradas_omie', to='painel.empresa')),
            ],
            options={
                'verbose_name': 'Família Ignorada Omie',
                'verbose_name_plural': 'Famílias Ignoradas Omie',
                'unique_together': {('empresa', 'nome')},
            },
        ),
    ]
