# Generated by Django 5.0 on 2025-12-18 03:47

import painel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_videotemplate_elementos_extras_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotemplate',
            options={},
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='arquivo_video',
            field=models.FileField(upload_to='templates_video/'),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='elementos_extras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='estilos_css',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_left',
            field=models.FloatField(default=10, validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_top',
            field=models.FloatField(default=30, validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='img_width',
            field=models.FloatField(default=20, validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_cor',
            field=models.CharField(default='#FFD700', max_length=7),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_left',
            field=models.FloatField(default=50, validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_tamanho',
            field=models.CharField(default='8vw', max_length=10),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='preco_top',
            field=models.FloatField(default=50, validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_cor',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_left',
            field=models.FloatField(default=50, validators=[painel.models.validar_porcentagem]),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_tamanho',
            field=models.CharField(default='5vw', max_length=10),
        ),
        migrations.AlterField(
            model_name='videotemplate',
            name='titulo_top',
            field=models.FloatField(default=10, validators=[painel.models.validar_porcentagem]),
        ),
    ]
