# Generated by Django 5.0 on 2025-12-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_alter_videotemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPropaganda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Nome interno para identificação', max_length=100)),
                ('arquivo_video', models.FileField(upload_to='propagandas/')),
                ('duracao', models.IntegerField(default=15, help_text='Duração em segundos (caso o vídeo não tenha metadados)')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='exibir_propagandas',
            field=models.ManyToManyField(blank=True, help_text='Selecione vídeos institucionais para intercalar', to='painel.videopropaganda'),
        ),
    ]
