# Generated by Django 6.0.6 on 2026-09-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_familiaignoradaomie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='orientacao',
            field=models.CharField(choices=[('HORIZONTAL', 'Horizontal (Padrão 16:9)'), ('HORIZONTAL_CUSTOM', 'Horizontal Customizada (16:9 Dividida)'), ('VERTICAL_DIR', 'Vertical 9:16 (Giro 90° Direita)'), ('VERTICAL_ESQ', 'Vertical 9:16 (Giro 90° Esquerda)')], default='HORIZONTAL', max_length=20),
        ),
    ]
