# Generated by Django 5.0 on 2025-12-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_videopropaganda_dispositivo_exibir_propagandas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição na TV (Menor número aparece primeiro)'),
        ),
        migrations.AddField(
            model_name='videopropaganda',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Ordem de exibição na playlist'),
        ),
        migrations.AddField(
            model_name='videotemplate',
            name='duracao',
            field=models.IntegerField(default=15, help_text='Duração do vídeo em segundos (Padrão para produtos)'),
        ),
        migrations.AlterField(
            model_name='videopropaganda',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Se desmarcado, não aparecerá na TV'),
        ),
        migrations.AlterField(
            model_name='videopropaganda',
            name='duracao',
            field=models.IntegerField(default=15, help_text='Duração em segundos'),
        ),
    ]
