# Generated by Django 6.0.6 on 2026-09-25 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_alter_dispositivo_orientacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='escala_fonte',
            field=models.PositiveSmallIntegerField(default=100, help_text='Percentual aplicado ao tamanho da fonte da tabela de preços. Permite compensar diferenças de tamanho e distância de cada TV.', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
