# Generated by Django 5.0 on 2026-02-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0010_produto_ordem_videopropaganda_ordem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='playlist',
            field=models.JSONField(blank=True, default=list, help_text='Estrutura ordenada da playlist'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='modo_exibicao',
            field=models.CharField(choices=[('TABELA', 'Apenas Tabela de Preços (Legado)'), ('VIDEO', 'Apenas Vídeos de Oferta (Legado)'), ('MISTO', 'Tabela + Vídeos Intercalados (Legado)'), ('PLAYLIST', 'Usar Playlist Personalizada (Nova)')], default='PLAYLIST', max_length=20),
        ),
    ]
