# Generated by Django 5.0 on 2026-02-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_dispositivo_playlist_alter_dispositivo_modo_exibicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='titulo_exibicao',
            field=models.CharField(blank=True, help_text='Título exibido no topo da TV (Ex: OFERTAS ESPECIAIS). Se vazio, usa o Nome.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nome',
            field=models.CharField(help_text='Ex: TV do Açougue (Identificação Interna)', max_length=100),
        ),
    ]
