# Generated by Django 5.0 on 2026-02-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0012_dispositivo_titulo_exibicao_alter_dispositivo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='playlist',
            field=models.JSONField(blank=True, default=list, help_text='Estrutura ordenada da playlist (Drag & Drop)'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='titulo_exibicao',
            field=models.CharField(blank=True, help_text='Título exibido no topo da TV. Se vazio, usa o Nome.', max_length=100, null=True),
        ),
    ]
