# Generated by Django 5.0 on 2026-02-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0013_alter_dispositivo_playlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Identificação interna para organização', max_length=100)),
                ('arquivo', models.FileField(upload_to='midias/')),
                ('tipo', models.CharField(choices=[('VIDEO', 'Vídeo'), ('IMAGEM', 'Imagem')], editable=False, max_length=10)),
                ('duracao', models.IntegerField(default=15, help_text='Duração em segundos (padrão)')),
                ('dados_estudio', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
