# Generated by Django 5.0 on 2026-02-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0014_midia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='exibir_propagandas',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='template_video',
        ),
        migrations.AddField(
            model_name='midia',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='VideoPropaganda',
        ),
        migrations.DeleteModel(
            name='VideoTemplate',
        ),
    ]
