# Generated by Django 5.0 on 2026-02-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0015_remove_dispositivo_exibir_propagandas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midia',
            name='dados_estudio',
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagem'), ('VIDEO', 'Vídeo'), ('SHAPE', 'Forma'), ('GROUP', 'Grupo')], default='TEXT', max_length=10)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Propriedades visuais e comportamentais da camada')),
                ('z_index', models.IntegerField(default=0, help_text='Ordem de empilhamento (maior fica por cima)')),
                ('is_locked', models.BooleanField(default=False, help_text='Bloqueia edição no editor visual')),
                ('is_visible', models.BooleanField(default=True, help_text='Define se a camada é renderizada')),
                ('midia', models.ForeignKey(help_text='Mídia (Canvas) onde esta camada está inserida', on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='painel.midia')),
                ('parent', models.ForeignKey(blank=True, help_text='Camada pai, caso esta camada pertença a um grupo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='painel.layer')),
            ],
            options={
                'verbose_name': 'Camada',
                'verbose_name_plural': 'Camadas',
                'ordering': ['z_index'],
            },
        ),
    ]
